### ISSUE TITLE
Add option to specify filename

### ISSUE THREAD

**Issue by shotrifork** [netsi1964/netsidownload#1]
The custom element should allow user to specify the filename that they want the file to have when downloaded.

Add a `filename` optional parameter

**Comment by netsi1964** [comment]
A new `filename` have been added, and also "intelligent" handling if no filename is specified.

In version 0.0.3
* the `data` value is tried to match a DOM element
* If an element is within HTML namespace
  * If a `textarea` or an element having a `value` attribute is discovered, default mimetype is set to text, otherwise it is set to html
* If an element is within SVG namespace, mime type will be set to svg
Approate default filenames are also implemented for the above tests
